import type { InsertMovie } from "@shared/schema";

export const movieDatabase: InsertMovie[] = [
  // Sci-Fi Classics
  {
    tmdbId: 335984,
    title: "Blade Runner 2049",
    overview: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    releaseDate: "2017-10-04",
    posterPath: "/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdropPath: "/sAtoMqDVhNDQBc3QJL3RF6hlBEy.jpg",
    genres: ["Science Fiction", "Drama"],
    runtime: 164,
    voteAverage: 7.6,
    voteCount: 8500,
    popularity: 85.6,
    originalLanguage: "en",
    adult: false,
    cinematicDna: {
      visualStyle: ["Neon-lit", "Atmospheric", "Cyberpunk"],
      pacing: "Slow Burn",
      narrativeStructure: "Character Study",
      themes: ["Identity", "Humanity", "Technology"]
    },
    moodTags: ["Thoughtful", "Mysterious", "Melancholic"],
    microGenres: ["Contemplative Sci-Fi", "Neo-Noir", "Philosophical Drama"]
  },
  {
    tmdbId: 329865,
    title: "Arrival",
    overview: "Taking place after alien crafts land around the world, an expert linguist is recruited by the military to determine whether they come in peace or are a threat.",
    releaseDate: "2016-11-10",
    posterPath: "/yImmxRokQ5KiEtBboGBkroHlrit.jpg",
    backdropPath: "/yOJOcbWJNFJF5P8GzMYl7G9QNWo.jpg",
    genres: ["Science Fiction", "Drama"],
    runtime: 116,
    voteAverage: 7.6,
    voteCount: 7200,
    popularity: 75.4,
    originalLanguage: "en",
    adult: false,
    cinematicDna: {
      visualStyle: ["Minimalist", "Atmospheric", "Cerebral"],
      pacing: "Slow Burn",
      narrativeStructure: "Non-linear",
      themes: ["Communication", "Time", "Understanding"]
    },
    moodTags: ["Thoughtful", "Mysterious", "Emotional"],
    microGenres: ["Contemplative Sci-Fi", "Linguistic Thriller", "Philosophical Drama"]
  },
  {
    tmdbId: 78,
    title: "Blade Runner",
    overview: "In the smog-choked dystopian Los Angeles of 2019, blade runner Rick Deckard is called out of retirement to terminate a quartet of replicants who have escaped to Earth seeking their creator for a way to extend their short life spans.",
    releaseDate: "1982-06-25",
    posterPath: "/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg",
    backdropPath: "/sAtoMqDVhNDQBc3QJL3RF6hlBEy.jpg",
    genres: ["Science Fiction", "Drama", "Thriller"],
    runtime: 117,
    voteAverage: 7.9,
    voteCount: 13000,
    popularity: 47.1,
    originalLanguage: "en",
    adult: false,
    cinematicDna: {
      visualStyle: ["Neon-lit", "Atmospheric", "Cyberpunk"],
      pacing: "Slow Burn",
      narrativeStructure: "Character Study",
      themes: ["Identity", "Humanity", "Technology"]
    },
    moodTags: ["Thoughtful", "Mysterious", "Melancholic"],
    microGenres: ["Contemplative Sci-Fi", "Neo-Noir", "Existential Drama"]
  },
  {
    tmdbId: 11,
    title: "Star Wars",
    overview: "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.",
    releaseDate: "1977-05-25",
    posterPath: "/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    backdropPath: "/4iamfQYpi2CL8TaoNqB3T54q8Ca.jpg",
    genres: ["Adventure", "Action", "Science Fiction"],
    runtime: 121,
    voteAverage: 8.2,
    voteCount: 19500,
    popularity: 98.7,
    originalLanguage: "en",
    adult: false,
    cinematicDna: {
      visualStyle: ["Epic", "Space Opera", "Classic"],
      pacing: "Energetic",
      narrativeStructure: "Hero's Journey",
      themes: ["Good vs Evil", "Coming of Age", "Hope"]
    },
    moodTags: ["Adventurous", "Energetic", "Playful"],
    microGenres: ["Space Opera", "Epic Adventure", "Coming of Age"]
  },
  {
    tmdbId: 1891,
    title: "The Empire Strikes Back",
    overview: "The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke.",
    releaseDate: "1980-05-17",
    posterPath: "/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
    backdropPath: "/3FDG8rRjcjnixv9kHHt32kAu8b6.jpg",
    genres: ["Adventure", "Action", "Science Fiction"],
    runtime: 124,
    voteAverage: 8.4,
    voteCount: 16000,
    popularity: 87.3,
    originalLanguage: "en",
    adult: false,
    cinematicDna: {
      visualStyle: ["Epic", "Space Opera", "Dark"],
      pacing: "Intense",
      narrativeStructure: "Empire Strikes Back",
      themes: ["Family", "Sacrifice", "Destiny"]
    },
    moodTags: ["Adventurous", "Mysterious", "Emotional"],
    microGenres: ["Space Opera", "Sequel", "Character Development"]
  },
  {
    tmdbId: 181808,
    title: "Star Wars: The Last Jedi",
    overview: "Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.",
    releaseDate: "2017-12-13",
    posterPath: "/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg",
    backdropPath: "/5Iw7zQTHVRBOYpA0V6z0utcC5rqLSo.jpg",
    genres: ["Adventure", "Action", "Science Fiction"],
    runtime: 152,
    voteAverage: 7.0,
    voteCount: 14500,
    popularity: 69.4,
    originalLanguage: "en",
    adult: false,
    cinematicDna: {
      visualStyle: ["Epic", "Space Opera", "Modern"],
      pacing: "Epic",
      narrativeStructure: "Three-Act",
      themes: ["Legacy", "Hope", "Balance"]
    },
    moodTags: ["Adventurous", "Energetic", "Emotional"],
    microGenres: ["Space Opera", "Legacy Sequel", "Epic Adventure"]
  },
  // Action Movies
  {
    tmdbId: 155,
    title: "The Dark Knight",
    overview: "Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and District Attorney Harvey Dent, but soon finds himself prey to a reign of chaos unleashed by a rising criminal mastermind.",
    releaseDate: "2008-07-18",
    posterPath: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdropPath: "/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg",
    genres: ["Action", "Crime", "Drama"],
    runtime: 152,
    voteAverage: 9.0,
    voteCount: 32000,
    popularity: 123.4,
    originalLanguage: "en",
    adult: false,
    cinematicDna: {
      visualStyle: ["Dark", "Gritty", "Epic"],
      pacing: "Intense",
      narrativeStructure: "Multi-layered",
      themes: ["Justice", "Chaos", "Heroism"]
    },
    moodTags: ["Energetic", "Adventurous", "Thoughtful"],
    microGenres: ["Superhero Drama", "Crime Epic", "Moral Complexity"]
  },
  {
    tmdbId: 49026,
    title: "The Dark Knight Rises",
    overview: "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department.",
    releaseDate: "2012-07-17",
    posterPath: "/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
    backdropPath: "/3bgtUfKQKNi3nJsAB5URpP2wdRt.jpg",
    genres: ["Action", "Crime", "Drama"],
    runtime: 165,
    voteAverage: 7.6,
    voteCount: 19500,
    popularity: 89.2,
    originalLanguage: "en",
    adult: false,
    cinematicDna: {
      visualStyle: ["Epic", "Gritty", "Grand"],
      pacing: "Epic",
      narrativeStructure: "Trilogy Conclusion",
      themes: ["Redemption", "Legacy", "Hope"]
    },
    moodTags: ["Energetic", "Adventurous", "Emotional"],
    microGenres: ["Superhero Epic", "Trilogy Finale", "Revolution Drama"]
  },
  {
    tmdbId: 272,
    title: "Batman Begins",
    overview: "Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.",
    releaseDate: "2005-06-10",
    posterPath: "/8RW2runSEc34PLeSKQ78RyAJAtn.jpg",
    backdropPath: "/phxiKFDvPeQj4AbkvJLmuZEieDU.jpg",
    genres: ["Action", "Crime", "Drama"],
    runtime: 140,
    voteAverage: 7.7,
    voteCount: 20000,
    popularity: 67.8,
    originalLanguage: "en",
    adult: false,
    cinematicDna: {
      visualStyle: ["Dark", "Realistic", "Grounded"],
      pacing: "Methodical",
      narrativeStructure: "Origin Story",
      themes: ["Fear", "Justice", "Transformation"]
    },
    moodTags: ["Thoughtful", "Energetic", "Mysterious"],
    microGenres: ["Superhero Origin", "Crime Drama", "Character Study"]
  },
  {
    tmdbId: 27205,
    title: "Inception",
    overview: "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible.",
    releaseDate: "2010-07-16",
    posterPath: "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    backdropPath: "/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    genres: ["Action", "Science Fiction", "Adventure"],
    runtime: 148,
    voteAverage: 8.3,
    voteCount: 29000,
    popularity: 89.7,
    originalLanguage: "en",
    adult: false,
    cinematicDna: {
      visualStyle: ["Surreal", "Architectural", "Layered"],
      pacing: "Complex",
      narrativeStructure: "Multi-layered",
      themes: ["Reality", "Memory", "Love"]
    },
    moodTags: ["Thoughtful", "Mysterious", "Adventurous"],
    microGenres: ["Mind-Bending Thriller", "Heist Film", "Philosophical Action"]
  },
  {
    tmdbId: 1726,
    title: "Iron Man",
    overview: "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
    releaseDate: "2008-04-30",
    posterPath: "/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
    backdropPath: "/cyecB7godNFaA8xLOnRSLYoFkXN.jpg",
    genres: ["Action", "Science Fiction", "Adventure"],
    runtime: 126,
    voteAverage: 7.6,
    voteCount: 24500,
    popularity: 98.1,
    originalLanguage: "en",
    adult: false,
    cinematicDna: {
      visualStyle: ["Tech-heavy", "Sleek", "Modern"],
      pacing: "Energetic",
      narrativeStructure: "Origin Story",
      themes: ["Technology", "Responsibility", "Redemption"]
    },
    moodTags: ["Energetic", "Playful", "Adventurous"],
    microGenres: ["Superhero Origin", "Tech Thriller", "Character Transformation"]
  },
  // Thrillers & Crime
  {
    tmdbId: 550,
    title: "Fight Club",
    overview: "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy.",
    releaseDate: "1999-10-15",
    posterPath: "/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg",
    backdropPath: "/87hTDiay2N2qWyX4Ds7ybXi9h8I.jpg",
    genres: ["Drama", "Thriller"],
    runtime: 139,
    voteAverage: 8.4,
    voteCount: 12000,
    popularity: 95.2,
    originalLanguage: "en",
    adult: false,
    cinematicDna: {
      visualStyle: ["Gritty", "Dark", "Stylized"],
      pacing: "Intense",
      narrativeStructure: "Twist Ending",
      themes: ["Identity", "Consumerism", "Masculinity"]
    },
    moodTags: ["Energetic", "Mysterious", "Rebellious"],
    microGenres: ["Psychological Thriller", "Anti-Establishment", "Mind-Bender"]
  },
  {
    tmdbId: 346,
    title: "Seven",
    overview: "Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the 'seven deadly sins' in this dark and haunting film.",
    releaseDate: "1995-09-22",
    posterPath: "/6yoghtyTpznpBik8EngEmJskVUO.jpg",
    backdropPath: "/8rFQp3f8U4PKnYaEqCHnKJWPaIV.jpg",
    genres: ["Crime", "Drama", "Mystery"],
    runtime: 127,
    voteAverage: 8.4,
    voteCount: 18000,
    popularity: 67.2,
    originalLanguage: "en",
    adult: false,
    cinematicDna: {
      visualStyle: ["Dark", "Gritty", "Rain-soaked"],
      pacing: "Slow Burn",
      narrativeStructure: "Detective Story",
      themes: ["Sin", "Justice", "Human Nature"]
    },
    moodTags: ["Mysterious", "Melancholic", "Thoughtful"],
    microGenres: ["Psychological Thriller", "Crime Noir", "Existential Horror"]
  },
  {
    tmdbId: 630,
    title: "The Usual Suspects",
    overview: "Held in an L.A. interrogation room, Verbal Kint attempts to convince the feds that a mythic crime lord, Keyser Soze, not only exists, but was also responsible for drawing him and his four partners into a multi-million dollar heist.",
    releaseDate: "1995-07-19",
    posterPath: "/99xJtLIVGYSdaRosHCa11vUd5Zx.jpg",
    backdropPath: "/mFZ9NMhJJZ6j7A2NGAV5O1AQsmh.jpg",
    genres: ["Drama", "Crime", "Thriller"],
    runtime: 106,
    voteAverage: 8.3,
    voteCount: 14500,
    popularity: 58.9,
    originalLanguage: "en",
    adult: false,
    cinematicDna: {
      visualStyle: ["Noir", "Shadowy", "Minimalist"],
      pacing: "Methodical",
      narrativeStructure: "Twist Ending",
      themes: ["Deception", "Truth", "Identity"]
    },
    moodTags: ["Mysterious", "Thoughtful", "Energetic"],
    microGenres: ["Crime Thriller", "Mind-Bender", "Heist Film"]
  },
  {
    tmdbId: 77,
    title: "Memento",
    overview: "Leonard Shelby is tracking down the man who raped and murdered his wife. The difficulty of locating his wife's killer, however, is compounded by the fact that he suffers from a rare, untreatable form of short-term memory loss.",
    releaseDate: "2000-09-05",
    posterPath: "/fX3p56jOzA24XFYhbLNUtj3Imdw.jpg",
    backdropPath: "/vLhY7Cp70f54SIXJnrGOq4QnJOQ.jpg",
    genres: ["Mystery", "Thriller"],
    runtime: 113,
    voteAverage: 8.2,
    voteCount: 16000,
    popularity: 73.5,
    originalLanguage: "en",
    adult: false,
    cinematicDna: {
      visualStyle: ["Noir", "Fragmented", "Polaroid"],
      pacing: "Reverse",
      narrativeStructure: "Non-linear",
      themes: ["Memory", "Identity", "Revenge"]
    },
    moodTags: ["Mysterious", "Thoughtful", "Energetic"],
    microGenres: ["Mind-Bending Thriller", "Reverse Chronology", "Memory Loss Drama"]
  },
  {
    tmdbId: 539,
    title: "Psycho",
    overview: "When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel.",
    releaseDate: "1960-06-16",
    posterPath: "/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg",
    backdropPath: "/9rVsW4n9RD26kY6Zr4u1UvGGhJ8.jpg",
    genres: ["Horror", "Mystery", "Thriller"],
    runtime: 109,
    voteAverage: 8.1,
    voteCount: 9500,
    popularity: 45.7,
    originalLanguage: "en",
    adult: false,
    cinematicDna: {
      visualStyle: ["Black and White", "Stark", "Claustrophobic"],
      pacing: "Methodical",
      narrativeStructure: "Classic Three-Act",
      themes: ["Identity", "Mother Complex", "Guilt"]
    },
    moodTags: ["Mysterious", "Melancholic", "Thoughtful"],
    microGenres: ["Psychological Horror", "Classic Thriller", "Hitchcockian"]
  }
];